apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-volume-jpereira
spec:
  volumes:
  - name: www-jpereira
  containers:
  - name: nginx-jpereira
    image: nginx
    volumeMounts:
    - name: www-jpereira
      mountPath: /usr/share/nginx/html/
  - name: git-jpereira
    image: alpine
    command: [ "sh", "-c", "apk add --no-cache git && git clone https://github.com/octocat/Spoon-Knife /www" ]
    volumeMounts:
    - name: www-jpereira
      mountPath: /www/
  restartPolicy: OnFailure


