{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jpereira-colored.serviceAccountName" . }}
  labels:
{{ include "jpereira-colored.labels" . | indent 4 }}
{{- end -}}
